In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
insurance_data= pd.read_csv("/content/sample_data/Insurance_TRAIN.csv")

In [ ]:
insurance_data.head()

id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
0  350957    Male   50  ...                   124      240         0
1  239788  Female   48  ...                   124      274         0
2  348272  Female   34  ...                   156      138         1
3   73940  Female   43  ...                   124      223         0
4  292871    Male   29  ...                   152      106         0

[5 rows x 12 columns]

In [ ]:
insurance_data.shape

(304887, 12)

In [ ]:
insurance_data.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage', 'Response'],
      dtype='object')

In [ ]:
insurance_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304887 entries, 0 to 304886
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   id                    304887 non-null  int64 
 1   Gender                304887 non-null  object
 2   Age                   304887 non-null  int64 
 3   Driving_License       304887 non-null  int64 
 4   Region_Code           304887 non-null  int64 
 5   Previously_Insured    304887 non-null  int64 
 6   Vehicle_Age           304887 non-null  object
 7   Vehicle_Damage        304887 non-null  object
 8   Annual_Premium        304887 non-null  int64 
 9   Policy_Sales_Channel  304887 non-null  int64 
 10  Vintage               304887 non-null  int64 
 11  Response              304887 non-null  int64 
dtypes: int64(9), object(3)
memory usage: 27.9+ MB


In [ ]:
insurance_data.describe()

id            Age  ...        Vintage       Response
count  304887.000000  304887.000000  ...  304887.000000  304887.000000
mean   190464.686973      38.832545  ...     154.293105       0.122357
std    109998.823015      15.520667  ...      83.713258       0.327698
min         1.000000      20.000000  ...      10.000000       0.000000
25%     95183.500000      25.000000  ...      82.000000       0.000000
50%    190485.000000      36.000000  ...     154.000000       0.000000
75%    285642.500000      49.000000  ...     227.000000       0.000000
max    381108.000000      85.000000  ...     299.000000       1.000000

[8 rows x 9 columns]

In [ ]:
insurance_data.Gender.value_counts()

Male      164823
Female    140064
Name: Gender, dtype: int64

In [ ]:
insurance_data.Vehicle_Age.value_counts()

1-2 Year     160244
< 1 Year     131823
> 2 Years     12820
Name: Vehicle_Age, dtype: int64

In [ ]:
insurance_data.Vehicle_Damage.value_counts()

Yes    153897
No     150990
Name: Vehicle_Damage, dtype: int64

In [ ]:
insurance_data.Previously_Insured.value_counts()

0    165116
1    139771
Name: Previously_Insured, dtype: int64

In [ ]:
insurance_data.Driving_License.value_counts()

1    304239
0       648
Name: Driving_License, dtype: int64

In [ ]:
insurance_data.Response.value_counts()

0    267582
1     37305
Name: Response, dtype: int64

In [ ]:
scalar =LabelEncoder()
insurance_data["Gender"] = scalar.fit_transform(insurance_data["Gender"])

In [ ]:
insurance_data.Gender.unique()

array([1, 0])

In [ ]:
scalar =LabelEncoder()
insurance_data["Vehicle_Age"] = scalar.fit_transform(insurance_data["Vehicle_Age"])

In [ ]:
insurance_data.Vehicle_Age.unique()

array([0, 1, 2])

In [ ]:
scalar =LabelEncoder()
insurance_data["Vehicle_Damage"] = scalar.fit_transform(insurance_data["Vehicle_Damage"])

In [ ]:
insurance_data.Vehicle_Damage.unique()

array([1, 0])

In [ ]:
features = insurance_data.drop("Response",axis=1)
target = insurance_data["Response"]

In [ ]:
trainx,testx,trainy,testy = train_test_split(features,target,test_size=0.3,random_state=40)

In [ ]:
print(trainx.shape,trainy.shape)

(213420, 11) (213420,)


In [ ]:
print(testx.shape,testy.shape)

(91467, 11) (91467,)


In [ ]:
testy

62761     0
99685     0
220460    0
56346     0
270589    0
         ..
280079    0
198766    0
164935    0
122793    1
205251    0
Name: Response, Length: 91467, dtype: int64

In [ ]:
#deep neural network, the neural network should have more hiddden layers
model = tf.keras.Sequential()
model.add(tf.keras.layers.InputLayer(11))
model.add(tf.keras.layers.Dense(32,activation="relu"))
model.add(tf.keras.layers.Dense(32,activation="relu"))
model.add(tf.keras.layers.Dense(16,activation="relu"))
model.add(tf.keras.layers.Dense(8,activation="relu"))
model.add(tf.keras.layers.Dense(1,activation="sigmoid"))
#model.add(tf.keras.layers.Dense(1,activation="linear")) for linear data give activation function as linear

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                384       
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 9         
Total params: 2,113
Trainable params: 2,113
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
pred= model.predict(testx)

In [ ]:
model.fit(trainx,trainy,epochs=5)

Epoch 1/5
6670/6670 [==============================] - 11s 2ms/step - loss: 0.3716 - accuracy: 0.8777
Epoch 2/5
6670/6670 [==============================] - 11s 2ms/step - loss: 0.3715 - accuracy: 0.8777
Epoch 3/5
6670/6670 [==============================] - 11s 2ms/step - loss: 0.3715 - accuracy: 0.8777
Epoch 4/5
6670/6670 [==============================] - 11s 2ms/step - loss: 0.3715 - accuracy: 0.8777
Epoch 5/5
6670/6670 [==============================] - 12s 2ms/step - loss: 0.3715 - accuracy: 0.8777


In [ ]:
pred.shape

(91467, 1)

In [ ]:
print(pred.max(),pred.min())

0.0 0.0
